---
- name: create service for deployment
  hosts: kubernetes
  # become: true
  user: ubuntu

  tasks:
  - name: create a service
    command: kubectl expose deployment abctech-project --type=LoadBalancer --name=my-service
